export const FETCH_INIT = "FETCH_INIT";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_RANDOM_SUCCESS = "FETCH_RANDOM_SUCCESS";
export const FETCH_RANDOM_FAILURE = "FETCH_RANDOM_FAILURE";
